export const cardsData = [
  {
    id: 1,
    title: "USERS",
    value: "720",
    button: "See all users",
    icon: "Group",
    arrowIcon: "ArrowDropUp",
    procentage: "+ 5%",
  },
  {
    id: 2,
    title: "ORDERS",
    value: "260",
    button: "View all orders",
    icon: "ShoppingCart",
    arrowIcon: "ArrowDropUp",
    procentage: "+ 2%",
  },
  {
    id: 3,
    title: "EARNINGS",
    value: "$4.6k",
    button: "View net earnings",
    icon: "MonetizationOn",
    arrowIcon: "ArrowDropUp",
    procentage: "+ 12%",
  },
  {
    id: 4,
    title: "MY BALANCE",
    value: "$7.6k",
    button: "See balance",
    icon: "AccountBalanceWallet",
    arrowIcon: "ArrowDropUp",
    procentage: "+ 5%",
  },
];
